linter:
  rules:
    avoid_classes_with_only_static_members: false
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_return_types_on_setters: true
    avoid_slow_async_io: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    control_flow_in_finally: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    iterable_contains_unrelated_type: true
    library_names: true
    library_prefixes: true
    list_remove_unrelated_type: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    non_constant_identifier_names: true
    constant_identifier_names: true
    overridden_fields: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_initializing_formals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_typing_uninitialized_variables: true
    recursive_getters: true
    slash_for_doc_comments: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_rethrow_when_possible: true
    valid_regexps: true
    avoid_returning_null_for_future: true
    close_sinks: true
    prefer_void_to_null: true
    unnecessary_statements: true
    avoid_returning_this: true
    avoid_void_async: true
    camel_case_extensions: true
    cascade_invocations: true
    only_throw_errors: true
    one_member_abstracts: true
    prefer_double_quotes: true
    prefer_final_in_for_each: true
    prefer_is_not_operator: true
    prefer_inlined_adds: true
    prefer_if_null_operators: true
    prefer_iterable_whereType: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    sort_child_properties_last: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_parenthesis: true
    unnecessary_string_interpolations: true
    unnecessary_string_escapes: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    sort_pub_dependencies: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    void_checks: true
