name: app
description: A client for reading Xianxia & Wuxia novels
version: 3.0.7+26

environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: ^2.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_markdown: ^0.6.6
  html: ^0.15.0
  path_provider: ^2.0.5
  provider: ^6.0.0
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.11
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/novels.json
    - assets/images/1x1.png
  fonts:
    - family: Material Design Icons
      fonts:
        - asset: assets/fonts/material-design-icons.ttf
